# Usar la imagen base de nginx
FROM nginx:latest

# Copiar el archivo index.html modificado al directorio donde nginx sirve contenido
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 para acceder al contenido web
EXPOSE 80


